title: YardRat 🦊
logo: assets/img/yardrat.jpg
description: >
  Nur durch strenge Spezialisierung kann der wissenschaftliche Arbeiter 
  tatsächlich das Vollgefühl, einmal und vielleicht nie wieder im Leben, 
  sich zu eigen machen: hier habe ich etwas geleistet, was dauern wird.
theme: jekyll-theme-minimal
